base_config: &BASE_CONFIG
    dataset_name: "physical" #"whole", "physical"
    # define channels to be read from data
    channel_names: ['U_level_idx_0', 'V_level_idx_0', 'OMEGA_level_idx_0', 'T_level_idx_0', 'U_level_idx_5', 'V_level_idx_5', 'OMEGA_level_idx_5', 'T_level_idx_5', 'U_level_idx_10', 'V_level_idx_10', 'OMEGA_level_idx_10', 'T_level_idx_10', 'U_level_idx_15', 'V_level_idx_15', 'OMEGA_level_idx_15', 'T_level_idx_15', 'U_level_idx_20', 'V_level_idx_20', 'OMEGA_level_idx_20', 'T_level_idx_20', 'U_level_idx_25', 'V_level_idx_25', 'OMEGA_level_idx_25', 'T_level_idx_25', 'U_level_idx_30', 'V_level_idx_30', 'OMEGA_level_idx_30', 'T_level_idx_30', 'U_level_idx_35', 'V_level_idx_35', 'OMEGA_level_idx_35', 'T_level_idx_35', 'U_level_idx_40', 'V_level_idx_40', 'OMEGA_level_idx_40', 'T_level_idx_40', 'U_level_idx_45', 'V_level_idx_45', 'OMEGA_level_idx_45', 'T_level_idx_45', 'U_level_idx_50', 'V_level_idx_50', 'OMEGA_level_idx_50', 'T_level_idx_50', 'U_level_idx_55', 'V_level_idx_55', 'OMEGA_level_idx_55', 'T_level_idx_55', 'U_level_idx_60', 'V_level_idx_60', 'OMEGA_level_idx_60', 'T_level_idx_60', 'U_level_idx_65', 'V_level_idx_65', 'OMEGA_level_idx_65', 'T_level_idx_65', 'U_level_idx_70', 'V_level_idx_70', 'OMEGA_level_idx_70', 'T_level_idx_70', 'U_level_idx_75', 'V_level_idx_75', 'OMEGA_level_idx_75', 'T_level_idx_75', 'U_level_idx_80', 'V_level_idx_80', 'OMEGA_level_idx_80', 'T_level_idx_80', 'U_level_idx_85', 'V_level_idx_85', 'OMEGA_level_idx_85', 'T_level_idx_85', 'U_level_idx_90', 'V_level_idx_90', 'OMEGA_level_idx_90', 'T_level_idx_90', 'U_level_idx_95', 'V_level_idx_95', 'OMEGA_level_idx_95', 'T_level_idx_95', 'U_level_idx_100', 'V_level_idx_100', 'OMEGA_level_idx_100', 'T_level_idx_100', 'U_level_idx_105', 'V_level_idx_105', 'OMEGA_level_idx_105', 'T_level_idx_105', 'U_level_idx_110', 'V_level_idx_110', 'OMEGA_level_idx_110', 'T_level_idx_110', 'U_level_idx_115', 'V_level_idx_115', 'OMEGA_level_idx_115', 'T_level_idx_115', 'U_level_idx_120', 'V_level_idx_120', 'OMEGA_level_idx_120', 'T_level_idx_120', 'U_level_idx_125', 'V_level_idx_125', 'OMEGA_level_idx_125', 'T_level_idx_125', 'U_level_idx_130', 'V_level_idx_130', 'OMEGA_level_idx_130', 'T_level_idx_130', 'U_level_idx_135', 'V_level_idx_135', 'OMEGA_level_idx_135', 'T_level_idx_135', 'U_level_idx_140', 'V_level_idx_140', 'OMEGA_level_idx_140', 'T_level_idx_140']
    comparison_channels: ["U_level_idx_30","V_level_idx_30","OMEGA_level_idx_30","T_level_idx_30"]
    #channel_names: ['UI_level_idx_0', 'VI_level_idx_0', 'WI_level_idx_0', 'EDens_level_idx_0', 'UI_level_idx_5', 'VI_level_idx_5', 'WI_level_idx_5', 'EDens_level_idx_5', 'UI_level_idx_10', 'VI_level_idx_10', 'WI_level_idx_10', 'EDens_level_idx_10', 'UI_level_idx_15', 'VI_level_idx_15', 'WI_level_idx_15', 'EDens_level_idx_15', 'UI_level_idx_20', 'VI_level_idx_20', 'WI_level_idx_20', 'EDens_level_idx_20', 'UI_level_idx_25', 'VI_level_idx_25', 'WI_level_idx_25', 'EDens_level_idx_25', 'UI_level_idx_30', 'VI_level_idx_30', 'WI_level_idx_30', 'EDens_level_idx_30', 'UI_level_idx_35', 'VI_level_idx_35', 'WI_level_idx_35', 'EDens_level_idx_35', 'UI_level_idx_40', 'VI_level_idx_40', 'WI_level_idx_40', 'EDens_level_idx_40', 'UI_level_idx_45', 'VI_level_idx_45', 'WI_level_idx_45', 'EDens_level_idx_45', 'UI_level_idx_50', 'VI_level_idx_50', 'WI_level_idx_50', 'EDens_level_idx_50', 'UI_level_idx_55', 'VI_level_idx_55', 'WI_level_idx_55', 'EDens_level_idx_55', 'UI_level_idx_60', 'VI_level_idx_60', 'WI_level_idx_60', 'EDens_level_idx_60', 'UI_level_idx_65', 'VI_level_idx_65', 'WI_level_idx_65', 'EDens_level_idx_65', 'UI_level_idx_70', 'VI_level_idx_70', 'WI_level_idx_70', 'EDens_level_idx_70', 'UI_level_idx_75', 'VI_level_idx_75', 'WI_level_idx_75', 'EDens_level_idx_75', 'UI_level_idx_80', 'VI_level_idx_80', 'WI_level_idx_80', 'EDens_level_idx_80', 'UI_level_idx_85', 'VI_level_idx_85', 'WI_level_idx_85', 'EDens_level_idx_85', 'UI_level_idx_90', 'VI_level_idx_90', 'WI_level_idx_90', 'EDens_level_idx_90']
    #comparison_channels: ['UI_level_idx_30', 'VI_level_idx_30', 'WI_level_idx_30', 'EDens_level_idx_30']
    base_dir: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data"
    # metadata file for the dataset
    metadata_json_path: "${base_dir}/${dataset_name}/data.json"

    # data 
    train_data_path: "${base_dir}/${dataset_name}/train"
    valid_data_path: "${base_dir}/${dataset_name}/test"
    train_tracer_data_path:  "${base_dir}/tracer/train"
    valid_tracer_data_path: "${base_dir}/tracer/test"
    exp_dir: "/glade/campaign/univ/uerf0005/modulus-makani/outputs_first_stage"
    n_years: 10
    img_shape_x: 288
    img_shape_y: 192

    # files used for normalization of the data
    min_path: "${base_dir}/${dataset_name}/stats/mins.npy"
    max_path: "${base_dir}/${dataset_name}/stats/maxs.npy"
    time_means_path:   "${base_dir}/${dataset_name}/stats/time_means.npy"
    global_means_path: "${base_dir}/${dataset_name}/stats/global_means.npy"
    global_stds_path:  "${base_dir}/${dataset_name}/stats/global_stds.npy"
    time_diff_means_path: "${base_dir}/${dataset_name}/stats/time_diff_means.npy"
    time_diff_stds_path: "${base_dir}/${dataset_name}/stats/time_diff_stds.npy"

    # architecture related 
    nettype: "SFNO"
    model_grid_type: "equiangular"
    sht_grid_type: "legendre-gauss"
    filter_type: "linear"
    scale_factor: 3
    embed_dim: 384
    num_layers: 8
    complex_activation: "real"
    normalization_layer: "none"
    hard_thresholding_fraction: 1.0
    use_mlp: !!bool True
    mlp_mode: "serial"
    mlp_ratio: 2
    separable: !!bool False
    operator_type: "dhconv"
    activation_function: "gelu"
    pos_embed: "none" # "none", "direct" or "frequency". For resoltuion invariance, use add_grid instead or use "frequency"

    # training parameters
    loss: "absolute squared geometric l2"
    channel_weights: "auto"
    lr:  0.00025 #0.00025
    n_eval_samples: 8760
    max_epochs: 3
    batch_size: 16
    weight_decay: 0.0

    # scheduler parameters
    scheduler: "ReduceLROnPlateau" # "StepLR" # "ReduceLROnPlateau" or "CosineAnnealingLR"
    scheduler_T_max: 70         #used for CosineAnnealingLR
    scheduler_factor: 0.1
    scheduler_patience: 400     #used for reduceLRonplateauuu78i
    scheduler_min_lr: 1e-7       # optional floor

    scheduler_step_size: 100 #used for StepLR
    scheduler_gamma: 0.5 #used for StepLR
    lr_warmup_steps: 0 #used for StepLR


    # general
    verbose: !!bool False

    # wireup stuff
    wireup_info: "mpi"
    wireup_store: "tcp"

    num_data_workers: 2
    num_visualization_workers: 2
    dt: 1 # how many timesteps ahead the model will predict
    n_history: 2 # how many previous timesteps to consider
    prediction_type: "iterative"
    prediction_length: 35 # applicable only if prediction_type == "iterative"
    n_initial_conditions: 5 # applicable only if prediction_type == "iterative"
    valid_autoreg_steps: 19 # number of autoregressive steps for validation, 20 steps in total

    # we make the "epochs" shorter so we have more reporting
    n_train_samples_per_epoch: 37968

    ics_type: "specify_number"
    save_raw_forecasts: !!bool True
    save_channel: !!bool False
    masked_acc: !!bool False
    maskpath: None
    perturb: !!bool False
    add_noise: !!bool False
    noise_std: 0.

    target: "default" # options default, residual
    normalize_residual: false


    normalization: "zscore" # options zscore or minmax or none

    # extra channels
    add_grid: !!bool True
    gridtype: "sinusoidal"
    grid_num_frequencies: 16
    roll: !!bool False
    add_zenith: !!bool True
    # invariants
    add_orography: !!bool True
    orography_path: "${base_dir}/physical/invariants/orography.nc"
    add_landmask: !!bool True
    landmask_path: "${base_dir}/physical/invariants/landsurf.nc"
    add_f107: !!bool False
    add_ap: !!bool False
    add_kp: !!bool False
    space_weather_train_path: "/glade/derecho/scratch/jiahuih/Data/whole/train/"
    space_weather_valid_path: "/glade/derecho/scratch/jiahuih/Data/whole/test/"
    space_weather_inf_path: "/glade/derecho/scratch/jiahuih/Data/whole/out_of_sample/"
    space_weather_means_path: "/glade/derecho/scratch/jiahuih/Data/whole/stats/global_means.npy"
    space_weather_stds_path: "/glade/derecho/scratch/jiahuih/Data/whole/stats/global_stds.npy"
    finetune: !!bool False
    tracer_finetune: !!bool True
    predict_delta: !!bool True
    resuming: True
    # logging options
    log_to_screen: !!bool True
    log_to_wandb: !!bool False
    log_video: 1 # if > 0 will log every i-th epoch
    save_checkpoint: "legacy"

    optimizer_type: "AdamW"
    optimizer_beta1: 0.9
    optimizer_beta2: 0.95
    optimizer_max_grad_norm: 32
    crop_size_x: None
    crop_size_y: None

    # required for validation and scoring
    inf_data_path: "${base_dir}/${dataset_name}/out_of_sample"
    tracer_inf_data_path: "${base_dir}/tracer/out_of_sample"

    # Weights and biases configuration
    wandb_name: None # If None, wandb will assign a random name, recommended
    wandb_group: "sfnonet development" # If None, will be "era5_wind" + config, but you can override it here
    wandb_project: "sfno architecture validation"
    wandb_entity: "sfno-large-model-training"

###########################################################################################################################
# 73 channels + Q base
###########################################################################################################################

# 1 GPUS, h=1, no cuda graphs

base_73chq: &BASELINE_73CHQ
    <<: *BASE_CONFIG

base_73chq_finetune: &BASELINE_73CHQ_FINETUNE
    <<: *BASELINE_73CHQ
    finetune: !!bool True
    lr: 1E-6
    scheduler: "CosineAnnealingLR"
    max_epochs: 3
    scheduler_T_max: 20

# current best single GPU model
sfno_linear_73chq_sc3_layers8_edim384_wstgl2:
    <<: *BASELINE_73CHQ
    wandb_group: "sfno_linear_73chq_sc3_layers8_edim384_wstgl2"

    embed_dim: 384
    num_layers: 8
    scale_factor: 3
    hard_thresholding_fraction: 1.0

    loss: "weighted absolute squared geometric l2"

    channel_weights: "auto"

sfno_linear_73chq_sc3_layers8_edim384_asgl2:
    <<: *BASELINE_73CHQ
    wandb_group: "sfno_linear_73chq_sc3_layers8_edim384_asgl2"

    # log_weights_and_grads: 10

    embed_dim: 384
    num_layers: 8
    scale_factor: 3
    hard_thresholding_fraction: 1.0

    optimizer_type: "Adam"

    loss: "absolute squared geometric l2"


###########################################################################################################################
# Tracer-coupled configuration
###########################################################################################################################

base_tracer: &BASE_TRACER
  <<: *BASE_CONFIG
  nettype: "/glade/campaign/univ/uerf0005/modulus-makani/makani/models/networks/tracer_sfno.py:CAMNetWithTracer"
  tracerset_name: "whole" # "whole" for run 01 UI channels, "tracer" for run 02 O channels
  # Tracer-specific parameters
  tracer_input_channels: 3
  tracer_output_channels: 3
  tracer_history_mode: "none"
  tracer_history_decay: 0.5

  physical_embed_dim: 384
  tracer_embed_dim: 384

  # Training adjustments
  batch_size: 4
  lr: 0.00001
  loss: "weighted absolute squared geometric l2"
  channel_weights: "auto"
  max_epochs: 15

  # Required runtime flags
  enable_synthetic_data: false
  enable_odirect: false
  enable_benchy: false
  save_checkpoint: "legacy"
  

# Example configuration
sfno_tracer_coupled:
  <<: *BASE_TRACER
  wandb_group: "sfno_tracer_coupled"
  embed_dim: 384
  num_layers: 8
  tracer_layers: 2
  max_epochs: 10
  resuming: !!bool True
  base_dir: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data"
  tracer_metadata_json_path: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/data.json"
  tracer_train_data_path: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/train"
  tracer_valid_data_path: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/test"
  tracer_inf_data_path: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/out_of_sample"
  min_path_tracer: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/mins.npy"
  max_path_tracer: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/maxs.npy"
  time_means_path_tracer:   "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/time_means.npy"
  global_means_path_tracer: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/global_means.npy"
  global_stds_path_tracer:  "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/global_stds.npy"
  time_diff_means_path_tracer: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/time_diff_means.npy"
  time_diff_stds_path_tracer: "/glade/derecho/scratch/jiahuih/Data_Process/processed_data/${tracerset_name}/stats/time_diff_stds.npy"

  tracer_normalization: "zscore"
  tracer_channel_names: ['UI_level_idx_0', 'UI_level_idx_5', 'UI_level_idx_10', 'UI_level_idx_15', 'UI_level_idx_20', 'UI_level_idx_25', 'UI_level_idx_30', 'UI_level_idx_35', 'UI_level_idx_40', 'UI_level_idx_45', 'UI_level_idx_50', 'UI_level_idx_55', 'UI_level_idx_60', 'UI_level_idx_65', 'UI_level_idx_70', 'UI_level_idx_75', 'UI_level_idx_80', 'UI_level_idx_85', 'UI_level_idx_90']
  #tracer_channel_names: [
  #          "O_level_idx_0",
  #          "O2_level_idx_0",
  #          "NO_level_idx_0",
  #          "O_level_idx_5",
  #          "O2_level_idx_5",
  #          "NO_level_idx_5",
  #          "O_level_idx_10",
  #          "O2_level_idx_10",
  #          "NO_level_idx_10",
  #          "O_level_idx_15",
  #          "O2_level_idx_15",
  #          "NO_level_idx_15",
  #          "O_level_idx_20",
  #          "O2_level_idx_20",
  #          "NO_level_idx_20",
  #          "O_level_idx_25",
  #          "O2_level_idx_25",
  #          "NO_level_idx_25",
  #          "O_level_idx_30",
  #          "O2_level_idx_30",
  #          "NO_level_idx_30",
  #          "O_level_idx_35",
  #          "O2_level_idx_35",
  #          "NO_level_idx_35",
  #          "O_level_idx_40",
  #          "O2_level_idx_40",
  #          "NO_level_idx_40",
  #          "O_level_idx_45",
  #          "O2_level_idx_45",
  #          "NO_level_idx_45",
  #          "O_level_idx_50",
  #          "O2_level_idx_50",
  #          "NO_level_idx_50",
  #          "O_level_idx_55",
  #          "O2_level_idx_55",
  #          "NO_level_idx_55",
  #          "O_level_idx_60",
  #          "O2_level_idx_60",
  #          "NO_level_idx_60",
  #          "O_level_idx_65",
  #          "O2_level_idx_65",
  #          "NO_level_idx_65",
  #          "O_level_idx_70",
  #          "O2_level_idx_70",
  #          "NO_level_idx_70",
  #          "O_level_idx_75",
  #          "O2_level_idx_75",
  #          "NO_level_idx_75",
  #          "O_level_idx_80",
  #          "O2_level_idx_80",
  #          "NO_level_idx_80",
  #          "O_level_idx_85",
  #          "O2_level_idx_85",
  #          "NO_level_idx_85",
  #          "O_level_idx_90",
  #          "O2_level_idx_90",
  #          "NO_level_idx_90",
  #          "O_level_idx_95",
  #          "O2_level_idx_95",
  #          "NO_level_idx_95",
  #          "O_level_idx_100",
  #          "O2_level_idx_100",
  #          "NO_level_idx_100",
  #          "O_level_idx_105",
  #          "O2_level_idx_105",
  #          "NO_level_idx_105",
  #          "O_level_idx_110",
  #          "O2_level_idx_110",
  #          "NO_level_idx_110",
  #          "O_level_idx_115",
  #          "O2_level_idx_115",
  #          "NO_level_idx_115",
  #          "O_level_idx_120",
  #          "O2_level_idx_120",
  #          "NO_level_idx_120",
  #          "O_level_idx_125",
  #          "O2_level_idx_125",
  #          "NO_level_idx_125",
  #          "O_level_idx_130",
  #          "O2_level_idx_130",
  #          "NO_level_idx_130",
  #          "O_level_idx_135",
  #          "O2_level_idx_135",
  #          "NO_level_idx_135",
  #          "O_level_idx_140",
  #          "O2_level_idx_140",
  #          "NO_level_idx_140"
  #      ]
