#PBS -A uerf0005                    
#PBS -N inference_tracer                
#PBS -q main                
#PBS -l walltime=02:00:00           
#PBS -l select=1:ncpus=16:ngpus=1:mem=64GB
#PBS -j oe                          
 
# Load necessary modules
module purge
module load ncarenv/23.09 intel-oneapi/2023.2.1 craype/2.7.23 cray-mpich/8.1.27
module load nvhpc/24.1
module load cuda/11.8
module load conda
 
# Activate your conda environment
conda activate fcn_afno_env
export MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED=1

cd /glade/campaign/univ/uerf0005/modulus-makani
export PYTHONPATH=$(pwd):$PYTHONPATH
  
# Print GPU and Torch availability information
nvidia-smi
python -c 'import torch; print(f"CUDA available: {torch.cuda.is_available()}"); print(f"Distributed package available: {torch.distributed.is_available()}")'
export MASTER_ADDR=127.0.0.1
export MASTER_PORT=12355
export WORLD_SIZE=1

# Run single-time tracer inference with torchrun so distributed env vars are set.

#torchrun --nproc_per_node=4 \
#    /glade/campaign/univ/uerf0005/modulus-makani/makani/inference.py \
#    --yaml_config="/glade/campaign/univ/uerf0005/modulus-makani/config/sfnonet.yaml" \
#    --config="sfno_tracer_coupled" \
#    --tracer_checkpoint_path="/glade/campaign/univ/uerf0005/modulus-makani/outputs_first_stage/sfno_tracer_coupled/01/training_checkpoints/" \
#    --pretrained_checkpoint_path="/glade/campaign/univ/uerf0005/modulus-makani/outputs_first_stage/sfno_linear_73chq_sc3_layers8_edim384_asgl2/03/training_checkpoints/" \
#    --run_num=01

torchrun --nproc_per_node=1 \
  --master-port=${MASTER_PORT} \
  makani/inference.py \
  --yaml_config=/glade/campaign/univ/uerf0005/modulus-makani/config/sfnonet.yaml \
  --config=sfno_tracer_coupled \
  --mode=single \
  --single_time="2015-03-16T09:00:00" \
  --batch_size=1 \
  --tracer_checkpoint_path=/glade/campaign/univ/uerf0005/modulus-makani/outputs_first_stage/sfno_tracer_coupled/01/training_checkpoints \
  --pretrained_checkpoint_path=/glade/campaign/univ/uerf0005/modulus-makani/outputs_first_stage/sfno_linear_73chq_sc3_layers8_edim384_asgl2/03/training_checkpoints \
  --run_num=01
